version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymcontroll_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"  # Porta para acessar o Laravel no navegador ou Postman
    depends_on:
      - db  # Garante que o banco suba antes do app
    networks:
      - gymcontroll
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: gymcontroll_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gymcontroll
      MYSQL_ROOT_PASSWORD: SenhaForte@123
      MYSQL_USER: gymuser
      MYSQL_PASSWORD: SenhaForte@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gymcontroll

volumes:
  db_data:

networks:
  gymcontroll:
